name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install dependencies
        run: >
          sudo apt-get -qqy install rsync libgmp-dev libmpfr-dev libgcc-10-dev
      - name: Build
        run: ./build.sh x86_64
